# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71da427a023d0264bfb27b528461c96ebb9c32a256efe88a48b610fc2266d91ef3fba5db85474c6575beea4e32042744d01d5a5f9585a4ad1bf06d7ca72df6a1

test:
  secret_key_base: 412466f5e0041d19fda4dce603d96e18bb8c0a19952248e2246adc8e65fe136c8215a5b26d9f15b2b7f09cd141960e1d9a80b48bdc0427d86beb13c2ce6a4f2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
